@echo off
title Aktivasi Microsoft Visio 2019 Tanpa Software - BagiTekno&cls&(net session >nul 2>&1)
if %errorLevel% GTR 0 (echo.&echo Aktivasi tidak bisa dilanjut, Anda harus Run CMD as administrator...&echo.&goto halt)
echo =====================================================================================&echo #Project: Aktivasi Microsoft Visio 2019 Tanpa Software&echo =====================================================================================&echo.&echo #Supported products:&echo - Microsoft Visio Standard 2019&echo - Microsoft Visio Professional 2019&echo.&echo.&echo Memulai proses aktivasi, silahkan tunggu...&echo.&(if exist "%ProgramFiles%\Microsoft Office\Office16\ospp.vbs" cd /d "%ProgramFiles%\Microsoft Office\Office16")&(if exist "%ProgramFiles(x86)%\Microsoft Office\Office16\ospp.vbs" cd /d "%ProgramFiles(x86)%\Microsoft Office\Office16")&tasklist /FI "IMAGENAME eq VISIO.EXE" 2>NUL | find /I /N "VISIO.EXE">NUL && taskkill /F /IM VISIO.EXE >nul&(REG DELETE "HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\Licensing" /f >nul 2>NUL)&(cscript //nologo ospp.vbs /setprt:1688 >nul || goto wshdisabled)&cscript //nologo ospp.vbs /inslic:"..\root\Licenses16\pkeyconfig-office.xrm-ms" >nul&(for /f %%x in ('dir /b ..\root\Licenses16\client-issuance*.xrm-ms') do cscript ospp.vbs /inslic:"..\root\Licenses16\%%x" >nul)&(for /f %%x in ('dir /b ..\root\Licenses16\visioprovl_kms*.xrm-ms') do cscript ospp.vbs /inslic:"..\root\Licenses16\%%x" >nul)&(for /f %%x in ('dir /b ..\root\Licenses16\visiopro2019vl_kms*.xrm-ms') do cscript ospp.vbs /inslic:"..\root\Licenses16\%%x" >nul)&echo.&echo =====================================================================================&echo Mengaktivasi Visio 2019 anda, silahkan tunggu...&echo =====================================================================================&cscript //nologo slmgr.vbs /ckms >nul&cscript //nologo ospp.vbs /setprt:1688 >nul&cscript //nologo ospp.vbs /unpkey:RJRJK >nul&cscript //nologo ospp.vbs /unpkey:7VCBB >nul&cscript //nologo ospp.vbs /unpkey:K2HT4 >nul&set i=1&cscript //nologo ospp.vbs /inpkey:9BGNQ-K37YR-RQHF2-38RQ3-7VCBB >nul||goto notsupported
:server
if %i% GTR 5 (goto busy) else if %i% LEQ 3 (set KMS=s1.keyms.id) else if %i% LEQ 5 (set KMS=e8.us.to)
cscript //nologo ospp.vbs /sethst:%KMS% >nul
:ato
echo.&cscript //nologo ospp.vbs /act | find /i "successful" > temp.txt && (echo.&echo Silahkan donasi via saweria.co/bagitekno2 untuk menyelesaikan aktivasi Visio anda.&echo.& if errorlevel 2 exit) || (echo Sepertinya butuh waktu lebih, silahkan tunggu... & echo. & echo. & set /a i+=1 & timeout /t 10 >nul & goto server)&timeout /t 7 >nul&explorer "https://saweria.co/bagitekno2"&echo.
set /P csawer=Apakah anda sudah donasi? (ketik YES jika sudah lalu Enter) : &echo.
if /i "%csawer%"=="YES" (echo.&echo =====================================================================================&echo.&type temp.txt&echo.&echo =====================================================================================&echo.&echo.&echo Jika sudah donasi dan Visio masih bermasalah, chat via Instagram @bagitekno_net&echo.&echo.&goto halt) else if "%csawer%"=="" (goto halt) else (goto halt)
:notsupported
echo.&echo =====================================================================================&echo Maaf, Microsoft Visio 2019 anda tidak support.&echo.&goto halt
:wshdisabled
echo =====================================================================================&echo.&echo Maaf, aktivasi gagal karena Windows Script Host access is disabled.&echo.&echo Solusinya, ikuti panduan pada video tutorial yang terbuka untuk mengizinkan Windows Script.&echo.&timeout /t 7 >nul&explorer "https://youtu.be/vqGMSQnWMIY"&goto halt
:busy
echo =====================================================================================&echo.&echo.&echo Maaf, aktivasi gagal karena koneksi internet anda tidak stabil.&echo.&echo Silahkan sambungkan Laptop anda ke WiFi lain kemudian ulangi lagi cara ini.&echo.&goto halt
:halt
cd %~dp0&del %0 >nul&pause >nul